import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:nahpu/services/database/database.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:nahpu/services/database/project_queries.dart';
import 'package:nahpu/services/providers/database.dart';
import 'package:uuid/uuid.dart';
import 'generated_migrations/schema.dart';

import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:drift/drift.dart';
import 'package:drift/native.dart';

import 'generated_migrations/schema_v6.dart' as v6;

void main() {
  late SchemaVerifier verifier;
  final nahpuDir = Directory('test/data');

  setUpAll(() {
    // GeneratedHelper() was generated by drift, the verifier is an api
    // provided by drift_dev.
    verifier = SchemaVerifier(GeneratedHelper());
  });

  Future<void> checkDBVersion(GeneratedDatabase db, int expectedVersion) async {
    final QueryRow result = await db.customSelect(
      'PRAGMA user_version;',
      readsFrom: const {}, // No tables are read, so the stream doesn't emit updates.
    ).getSingle();

    final int userVersion = result.data['user_version'] as int;
    expect(userVersion, expectedVersion);
  }

  Future<InitializedSchema> setupSchema(int schemaVersion) async {
    return await verifier.schemaAt(schemaVersion);
  }

  Future<GeneratedDatabase> setupDB(InitializedSchema schema, int schemaVersion,
      {bool forWrite = false}) async {
    if (forWrite) {
      final db = Database.forMigrationTesting(schema.newConnection());
      await verifier.migrateAndValidate(db, schemaVersion);
      return db;
    } else if (schemaVersion == 6) {
      return v6.DatabaseAtV6(schema.newConnection());
    } else {
      return Database.forMigrationTesting(schema.newConnection());
    }
  }

  Future<void> insertProject(GeneratedDatabase db, int schemaVersion,
      {ProjectData? projectData, String? projectName}) async {
    if (projectData != null) {
      await db.into((db as Database).project).insert(projectData);
      return;
    }

    if (schemaVersion == 6) {
      await db.into((db as v6.DatabaseAtV6).project).insert(
          v6.ProjectCompanion.insert(uuid: Uuid().v1(), name: projectName!));
    } else {
      await db.into((db as Database).project).insert(
          ProjectCompanion.insert(uuid: Uuid().v1(), name: projectName!));
    }
  }

  Future<void> writeDB(Database db, String name) async {
    final nahpuDir = Directory('test/data');
    final outputPath = File(p.join(nahpuDir.path, '$name.sqlite3'));
    await db.exportInto(outputPath);
  }

  QueryExecutor openConnection(String name) {
    final nahpuDir = Directory('test/data');
    final outputPath = File(p.join(nahpuDir.path, '$name.sqlite3'));
    return NativeDatabase.createInBackground(outputPath, logStatements: true);
  }

  test('end-to-end', () async {
    final container = ProviderContainer();
    addTearDown(container.dispose);

    // Setup destination/current db
    // final currSchema = await setupSchema(6);
    // var name = 'current';
    // var currDB = await setupDB(currSchema, 6);
    // await checkDBVersion(currDB, 6);
    // await insertProject(currDB, 6, '$name project');
    // await currDB.close();

    // final currDBWrite =
    //     await setupDB(currSchema, 6, forWrite: true) as Database;
    // final currProjects = await ProjectQuery(currDBWrite).getAllProjects();
    // print(currProjects);
    // await writeDB(currDBWrite, name);
    // await currDBWrite.close();

    // // Setup to-be-merged db
    final mergeSchema = await setupSchema(7);
    final name = 'db';
    var mergeDB = await setupDB(mergeSchema, 7);
    await checkDBVersion(mergeDB, 7);
    final projectPath = File(p.join(nahpuDir.path, 'project.json'));
    final projects = (jsonDecode(await projectPath.readAsString()) as List)
        .map((e) => ProjectData.fromJson(e))
        .toList();

    final sitesPath = File(p.join(nahpuDir.path, 'site.json'));
    final sites = (jsonDecode(await sitesPath.readAsString()) as List)
        .map((e) => SiteData.fromJson(e))
        .toList();

    for (ProjectData project in projects) {
      await mergeDB.into((mergeDB as Database).project).insert(project);
    }

    for (SiteData site in sites) {
      await mergeDB.into((mergeDB as Database).site).insert(site);
    }

    await mergeDB.close();

    mergeDB = await setupDB(mergeSchema, 7, forWrite: true);
    await writeDB(mergeDB as Database, name);
    await mergeDB.close();

    // final qe = openConnection(name);
    // final checkMergeDB = Database.forMigrationTesting(qe);
    // await checkDBVersion(checkMergeDB, 7);
    // await checkMergeDB.close();

    // // final outputPath = File(p.join(nahpuDir.path, 'db.sqlite3'));

    // // final dbAccess =
    // //     container.read(databaseFromPathProvider(dbFile: outputPath));
    // // final projects = await ProjectQuery(dbAccess).getAllProjects();
    // // final jsonPath = File(p.join(nahpuDir.path, 'projects_B_v7.json'));

    // // await jsonPath.writeAsString(projects[0].toJsonString());

    // print(projects);

    // await dbAccess.close();
  });
}
